# Generated by Django 5.1.4 on 2025-02-15 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPDM2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='login_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DPDM2.login'),
            preserve_default=False,
        ),
    ]
